Project2
acolombo1/Mobile-Portfolio pull request #1
Opened 2022-03-17 21:30 UTC by acolombo1

Add all the structure of the HTML and all the CSS code for the mobile portfolio look complete, and the images, and made a slight change to .gitignore.

2022-03-17 22:50 UTC, RolandM99 requested changes
Hi @acolombo1  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._
- [x] Please, Kindly add a descriptive title for your Pull Request and a short summary describing what changes you implemented in more detail inside it.
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Rolandm99 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 22:50 UTC, RolandM99 commented on index.html
> +          <div>Aldo Colombo</div>
To respect HTML best practices, the logo should be wrapped with a `<a>` tag with a link instead of a `<div>` tag. Please, kindly replace the `div` tag with an `a` tag.

2022-03-17 22:50 UTC, RolandM99 commented on index.html
> +        </div>
- [ ] Good job so far by implementing the design almost similar to the Figma design. But, to make your code more professional, I think It would be better to implement the list of items by using the `<ul>` tag to the group and each element a ` li` . Add also a working link with the `<a>`  tag for each element.

2022-03-17 22:50 UTC, RolandM99 commented on index.html
> +          <img src="img/git.png" alt="Github">
- [ ] The link to the Github icon is broken. 

![image](https://user-images.githubusercontent.com/71874425/158905078-d3711930-e84f-4077-bf96-3e672f9bf260.png)
Kindly, fix it.

2022-03-17 22:50 UTC, RolandM99 commented on style.css
> +  font-style: normal;
- [ ] Make sure that you use the same font-style with the Figma design.
### Figma design: 
![image](https://user-images.githubusercontent.com/71874425/158906502-22123ed7-3e66-4987-959a-e59d8cb88e84.png)
### your design : 
![image](https://user-images.githubusercontent.com/71874425/158906613-fc5ce885-2c65-4848-9097-64e1362752e2.png)

2022-03-17 23:34 UTC, acolombo1 commented on index.html
> +          <div>Aldo Colombo</div>
OK, where should the link point to? Shall I leave it empty for now?

2022-03-18 00:25 UTC, RolandM99 commented on index.html
> +          <div>Aldo Colombo</div>
To the headline page, just implement it like this :  `<a href="#" >Aldo Colombo</a>`

2022-03-18 01:47 UTC, acolombo1 commented
In sum, implement HTML with semantic tags, wrapped everything in a cellphone-looking box, which acts as a flex container which in turn contains several flex containers nested. Using flex column and row directions determine the layout, add a background.

2022-03-18 02:43 UTC, acolombo1 commented
Please notice that Webhint is broken. I re-checked my previously correct project (Welcome to Microverse), after a readme.md change, and now it throws the same error (AbortController is not defined). Take a look at: https://github.com/acolombo1/Project-1/pull/6

2022-03-18 02:55 UTC, smunozmo approved these changes
Hi @acolombo1 , 👋 

Your project is complete! You did an amazing job with the design, congratulations!. There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

### APPROVED! 👏 👏 👏 

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>


Cheers and Happy coding! 🤓 

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 03:00 UTC, merged